#!/bin/bash
 clear
 saisie(){
    echo "  
           "
    echo "       Bien vénu dans mon projrt SYS !"
    echo "     a ) Information des utilisateurs enrégistrés il y a trois jours !"
    echo "     b ) Aquisition, installation et lancement de l'environnement XAMP !"
    echo "     c ) Archivage des élèments du repertoire personnel qui ont été modifié   
            par l'utilisateur sudoers il y a deux jours dans un périphérique externe !"
    echo "     d ) Information sur l'utilisation du disque, de la mémoire, du processeur et de la SWAP !"
    echo "     q/Q ) Pour quitter !" 
 }
 saisie

 jr=backup -$(date +%d+%n+%y)
 archive=${2:-$jr}
 

 lecture(){
    read -r rep
  }
 lecture

 case $rep in
    a)  w | cut -d '' -f 1 - | grep -v USER | sort -u ;;

    b)  wget http://apachefriends.org/download.html/xampp-linux-x64-5.6.3-0-installer.run
        sudo apt-get install ia32-lib
        sudo tar xvfz ./xampp-linux- *.tar.gz
        sudo chmod +x xampp-linux-x64-5.6.3-0-installer.run
        sudo ./xamp-linux-x64-5.6.3-0-installer.run
        sudo /opt/lampp/lamppstart ;;

    c)  tar zvcf "$archive.tar.gz" ~/ ;;

    d) vmstat;; 

    q) exit ;;

    Q) exit ;;

    *) echo "Erreur de saisi ou choix inconu !" ;;    
    
 esac
